CREATE TABLE Users (
  UserID INT PRIMARY KEY IDENTITY(1, 1),
  Username NVARCHAR(50) NOT NULL UNIQUE,
  Email NVARCHAR(100) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
  LastLogin DATETIME2
);
CREATE TABLE Books (
  BookID INT PRIMARY KEY IDENTITY(1, 1),
  Title NVARCHAR(255) NOT NULL,
  Author NVARCHAR(100) NOT NULL,
  PublicationYear INT,
  AddedBy INT NOT NULL,
  AddedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
  FOREIGN KEY (AddedBy) REFERENCES Users(UserID)
);
CREATE TABLE Ratings (
  RatingID INT PRIMARY KEY IDENTITY(1, 1),
  UserID INT NOT NULL,
  ItemID INT NOT NULL,
  ItemType NVARCHAR(10) NOT NULL CHECK (ItemType IN ('Book')),
  Score DECIMAL(3, 1) NOT NULL CHECK (
    Score >= 0
    AND Score <= 10
  ),
  Comment NVARCHAR(1000),
  CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  CONSTRAINT UC_UserItem UNIQUE (UserID, ItemID, ItemType)
);